class CuestionarioBloque{
  Map<int, List> drogodependencia = {
    0: ['1.- ¿De dónde viene la palabra adicto?',
      'De griego "Pistis"',
      'Del latín "Addictus"',
      'De latín "Vitium"'],
    1: ['2.- Menciona los 4 tipos de consumo.',
      'Experimental, ocasional, habitual, crónico compulsivo.',
      'A diario, frecuente, de vez en cuando, ocasional.',
      'Con los amigos, en fiestas, en mi casa, en reuniones sociales.'],
    2: ['3.- ¿Cuáles son los 3 tipos de adicciones?',
      'Compras compulsivas, consumo de alcohol, relaciones neuróticas.',
      'Actividades, relaciones y sustancias.',
      'Adicción a objetos, personas y drogas.'],
    3: ['4.- ¿Cómo saber si un hábito se puede convertir en una adicción?',
      'Si se hace a escondidas y si genera problemas.',
      'Si se hace a diario.',
      'Si se me resulta agradable y desagradable.'],
    4 : ['5.- ¿Cuántas sustancias tóxicas contienen un cigarro de tabaco?',
      'Más de 100.',
      'Más de 50.',
      'Más de 4,000.'],
    5: ['6.- ¿Cuál es la “mamá” de las drogas?',
      'La cocaína.',
      'El alcohol.','La heroína'],
    6: ['7.- ¿Qué características debe tener una sustancia para que se considere como una \"droga\"?',
      'Que genere ansiedad, dependencia y tolerancia.',
      'Que genere sensación de placer.',
      'Que genere sentimientos de culpa.'],
    7: ['8.- ¿Es lo mismo estar \"drogado\" a estar "borracho"?',
      'No',
      'Depende del grado de embriaguez',
      'Si'],
    8:['9.- ¿Cuáles son los 4 tipos de bebedores?',
      'Bebedor compulsivo, bebedor tranquilo, bebedor agresivo, bebedor triste.',
      'Bebedor social, bebedor fuerte, bebedor problema, alcohólico.',
      'Bebedor agresivo, bebedor alegre, bebedor conversador, bebedor tranquilo.']
  };

  Map<int, List> liderazgo ={
    0: ['¿Que es liderazgo',
      'Influencia, caracter, ejemplo',
      'Voluntad, esfuerzo, empatia',
      'Vision, tenacidad. solidaridad'],
    1: ['¿Cuales son las tres responsabilidades de un lider?',
      'Cuidar de las personas',
      'Crear identidad, vision y cultura',
      'Ayudar a los que necesitan'],
    2: ['¿Cuál es el mensaje central de la historia del basquetbolista Irving Magic Jhonson?',
      'La influencia',
      'La voluntad',
      'El caracter'],
    3: ['¿Cual es el mensaje central de la historia de Butch O\'Hare',
      'La voluntad',
      'El esfuerzo',
      'El caracter'],
    4: ['¿Cual es la conducta que tienes que cambiar hoy para mejorar como padre de familia?'],
    5: ['En una escala del 1 al 10, ¿Cómo calificas al liderazgo como cualidad en tu vida?']
  };

  Map<int, List> liderazgo2 = {
    0: ['Como padre o madre de familia escribe la misión y visión de tu hogar.',
    'Mision',
    'Vision'],
    1: ['Cita a tu hijo/a y hazle las siguientes preguntas y escribe su respuesta. Cuando tengas mi edad, ¿Te gustaría ser como yo?',
      'Si',
      'No',
      'No lo se'],
    2: ['¿Por qué lo consideras así?']
  };
}
